name: ROS 2 Humble CI

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu runner

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up ROS 2 Humble (using ros2/setup-ros action)
      - name: Set up ROS 2 Humble
        uses: ros2/setup-ros@v0.1
        with:
          ros-distro: humble  # Set the ROS 2 distro to Humble

      # 3. Install system dependencies and ROS dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-rosdep

      - name: Install ROS dependencies using rosdep
        run: |
          source /opt/ros/humble/setup.bash
          rosdep update  # Update rosdep database
          rosdep install --from-paths src --ignore-src -r -y  # Install dependencies

      # 4. Build the workspace (without tests)
      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install  # Build the ROS 2 workspace

      
