name: ROS 2 Humble Build and Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest  
    
    container:
      image: osrf/ros:humble-desktop  

    strategy:
      matrix:
        os: [ubuntu-22.04]  
      fail-fast: false

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Install dependencies inside the ROS 2 container
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-vcstool python3-colcon-common-extensions python3-rosdep

      # 3. Install ROS dependencies using rosdep
      - name: Install ROS dependencies using rosdep
        run: |
          /bin/bash -c "source /opt/ros/humble/setup.bash && \
            if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then \
              rosdep init; \
            fi && \
            rosdep update && \
            rosdep install --from-paths src --ignore-src -r -y"

      # 4. Build the workspace using colcon
      - name: Build the workspace
        run: |
          /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install --parallel-workers 1"

     
