name: ROS 2 Humble Build and Test

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch (or replace with your branch)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the 'main' branch (or replace with your branch)

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Using GitHub-hosted Ubuntu runner
    
    container:
      image: osrf/ros:humble-desktop  # Use ROS 2 Humble Docker container

    strategy:
      matrix:
        os: [ubuntu-22.04]  # Ensure we use Ubuntu 22.04, the official OS for ROS 2 Humble
      fail-fast: false

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Install dependencies inside the ROS 2 container
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-vcstool python3-colcon-common-extensions python3-rosdep

      # 3. Install ROS dependencies using rosdep
      - name: Install ROS dependencies using rosdep
        run: |
          source /opt/ros/humble/setup.bash  # Now this will work inside the container
          rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # 4. Build the workspace using colcon
      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --parallel-workers 1
